config/routes.rb
Rails.application.routes.draw do
  resources :products, only: %i[index show edit destroy new create update]
  resources :warehouses, only: %i[index show edit destroy new create update]
  resources :stocks, only: %i[index new show create]
  resources :orders, only: %i[index new show create] do
    resources :order_items, only: %i[create]
  end
  # /orders/:order_id/order_items/:id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  has_many :order_items
  has_many :products, through: :order_items

  validates :customer_name, presence: true

  before_validation :assign_uuid

  private

  def assign_uuid
    return unless new_record? || uuid.empty?

    generated_uuid = ''
    presence = true

    while presence == true
      generated_uuid = SecureRandom.uuid

      presence = false unless Order.exists?(uuid: generated_uuid)
    end

    self.uuid = generated_uuid
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :stocks
  has_many :order_items
  has_many :warehouses, through: :stocks
  has_many :orders, through: :order_items

  validates :name, presence: true
  validates :sku, presence: true, uniqueness: { case_sensitive: false }
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :warehouse

  validates :count, presence: true, numericality: { greater_than: 0 }
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :stocks, dependent: :destroy
  has_many :products, through: :stocks
  has_many :orders

  validates :city, presence: true
  validates :province, presence: true

  def full_address
    "#{street}, #{city}, #{province}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order

  def create
    @order_item = OrderItem.new(order_items_params)

    if @order_item.save
      redirect_to order_path(@order)
    end
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end

  def order_items_params
    params.require(:order_item).permit(:order_id, :quantity, :product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show]
  before_action :set_form_dependencies, only: %i[new]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def show
    @order_item = @order.order_items.build
    @products = Product.all
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_form_dependencies
    @warehouses = Warehouse.all
  end

  def order_params
    params.require(:order).permit(:warehouse_id, :customer_name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :assign_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash.notice = 'Successfully created a product!'

      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash.notice = 'Successfully updated the product!'

      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy!

    flash.notice = "Successfully deleted product #{@product.id}!"
    redirect_to products_path
  end

  private

  def assign_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :sku)
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[show]
  before_action :set_form_dependencies, only: %i[new edit]

  def index
    @stocks = Stock.all
  end

  def show;  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to stock_path(@stock)
    else
      render :new
    end
  end

  private

  def set_form_dependencies
    @warehouses = Warehouse.all
    @products = Product.all
  end

  def set_stock
    @stock = Stock.find(params[:id])
  end

  def stock_params
    params.require(:stock).permit(:product_id, :warehouse_id, :count)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :assign_warehouse, only: %i[show edit update destroy]
  
  def index
    @warehouses = Warehouse.all
  end

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      flash.notice = 'Successfully created a warehouse!'

      redirect_to warehouse_path(@warehouse)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      flash.notice = 'Successfully updated the warehouse!'

      redirect_to warehouse_path(@warehouse)
    else
      render :edit
    end
  end

  def destroy
    @warehouse.destroy!

    flash.notice = "Successfully deleted warehouse #{@warehouse.id}!"
    redirect_to warehouses_path
  end

  private

  def assign_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:street, :city, :province)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def render_error(record, attr)
    return if record.errors[attr].empty?

    content_tag(
      :div,
      id: "#{record.class.name.titleize.parameterize(separator: '_')}_#{attr}_errors",
      class: 'alert alert-danger'
    ) do
      render_errors(record, attr)
    end
  end

  private

  def render_errors(record, attr)
    errors = record.errors[attr].map do |error|
      content_tag(:div, error, class: 'error')
    end

    safe_join(errors)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= form_with model: order_item, remote: false, url: order_order_items_path(order), method: :post do |f| %>
  <%= f.hidden_field :order_id %>
  <%= f.select :product_id, products.map { |p| [p.name, p.id] } %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit "Add Order Item", class: "btn btn-primary" %>
<% end %>

app/views/orders/index.html.erb
<%= link_to "new", new_order_path, class: "btn btn-primary" %>

app/views/orders/new.html.erb
<%= form_with model: @order, remote: false do |f| %>
  <%= f.label :customer_name %>
  <%= f.text_field :customer_name %>
  <%= f.label :warehouse %>
  <%= f.select :warehouse_id,
               @warehouses.map { |w| [w.full_address, w.id] } %>
  <%= f.submit "Save Order", class: "btn btn-success" %>
<% end %>

app/views/orders/show.html.erb
Cx: <%= @order.customer_name %>
<br />
Warehouse: <%= @order.warehouse.full_address %>
<hr />

<h4>Add a new order</h4>
<%= render "order_items/form", order_item: @order_item, order: @order, products: @products %>
<hr />

<% @order.order_items.each do |order_item| %>
  <% next if order_item.new_record? %>

  <%= order_item.product.name %> - (<%= order_item.quantity %>)
  <hr />
<% end %>

app/views/products/_form.html.erb
<%= form_with model: product, local: true, id: "product-form" do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= render_error(product, :name) %>
  </div>
  <div class="form-group">
    <%= f.label :sku %>
    <%= f.text_field :sku, class: "form-control" %>
    <%= render_error(product, :sku) %>
  </div>
  <%= f.submit "Save Product", class: "btn btn-primary", id: "submit-button" %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing Product (ID: <%= @product.id %>)</h1>

  <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>

<table id="products-table">
  <thead>
    <tr>
      <th>SKU</th>
      <th>Name</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr id="product--<%= product.id %>">
        <td id="product--<%= product.id %>_sku">
          <%= product.sku %>
        </td>
        <td id="product--<%= product.id %>_name">
          <%= product.name %>
        </td>
        <td id="product--<%= product.id %>_updated_at">
          <%= product.updated_at.strftime('%m-%d-%Y') %>
        </td>
        <td id="product--<%= product.id %>_actions">
          <%= link_to "Show", product_path(product) %>
          <%= link_to "Edit", edit_product_path(product) %>
          <%= link_to "Delete",
                      product_path(product),
                      class: "delete",
                      method: :delete,
                      data: {
                        confirm: "Are you sure you want to delete this product?"
                      } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>

  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<h1>Product</h1>
<hr />
<table class="table">
  <tbody>
    <tr>
      <td>Name</td>
      <td id="product--<%= @product.id %>_name">
        <%= @product.name %>
      </td>
    </tr>
    <tr>
      <td>SKU</td>
      <td id="product--<%= @product.id %>_sku">
        <%= @product.sku %>
      </td>
    </tr>
  </tbody>
</table>

app/views/shared/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="alert alert-<%= flash[:notice].present? ? 'success' : 'danger' %>">
    <%= flash[:notice] || flash[:alert] %>
  </div>
<% end %>

app/views/stocks/_form.html.erb
<%= form_with model: stock, local: true, id: "warehouse-form" do |f| %>
  <div class="form-group">
    <%= f.select :warehouse_id,
                 @warehouses.all.map { |w| [w.full_address, w.id] } %>
  </div>
  <div class="form-group">
    <%= f.select :product_id, @products.all.map { |p| [p.name, p.id] } %>
  </div>
  <div class="form-group">
    <%= f.label :count %>
    <%= f.text_field :count, class: "form-control" %>
  </div>
  <%= f.submit "Save Stock", class: "btn btn-primary", id: "submit-button" %>
<% end %>

app/views/stocks/edit.html.erb
<div class="container">
  <h1>Editing Warehouse (ID: <%= @warehouse.id %>)</h1>

  <%= render 'form', warehouse: @warehouse %>
</div>

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<%= link_to "New Stock", new_stock_path, class: "btn btn-primary" %>
<table id="stocks-table">
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Stock Count</th>
      <th>Warehouse</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr id="stock--<%= stock.id %>">
        <td id="stock--<%= stock.id %>_product">
          <%= stock.product.name %>
        </td>
      </tr>
      <tr id="stock--<%= stock.id %>">
        <td id="stock--<%= stock.id %>_count">
          <%= stock.count %>
        </td>
      </tr>
      <tr id="stock--<%= stock.id %>">
        <td id="stock--<%= stock.id %>_warehouse">
          <%= stock.warehouse.street + " " + stock.warehouse.city + " " + stock.warehouse.province %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/new.html.erb
<div class="container">
  <h1>New Stock</h1>

  <%= render "form", stock: @stock %>
</div>

app/views/stocks/show.html.erb
<h1>Stock</h1>
<hr />
<table class="table">
  <tbody>
    <tr>
      <td>Product Name</td>
      <td id="stock--<%= @stock.id %>_product_id_name">
        <%= @stock.product.name %>
      </td>
    </tr>
    <tr>
      <td>Count</td>
      <td id="stock--<%= @stock.id %>_count">
        <%= @stock.count %>
      </td>
    </tr>
    <tr>
      <td>Province</td>
      <td id="warehouse--<%= @stock.warehouse.id %>_province">
        <%= @stock.warehouse.full_address %>
      </td>
    </tr>
  </tbody>
</table>

app/views/warehouses/index.html.erb
<h1>Warehouses</h1>

<%= link_to 'New Warehouse', new_warehouse_path, class: 'btn btn-primary' %>

<table id="warehouses-table">
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>Province</th>
    </tr>
  </thead>
  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr id="warehouse--<%= warehouse.id %>">
        <td id="warehouse--<%= warehouse.id %>_street">
          <%= warehouse.street %>
        </td>
        <td id="warehouse--<%= warehouse.id %>_city">
          <%= warehouse.city %>
        </td>
        <td id="warehouse--<%= warehouse.id %>_province">
          <%= warehouse.province %>
        </td>
        <td id="warehouse--<%= warehouse.id %>_actions">
          <%= link_to "Show", warehouse_path(warehouse) %>
          <%= link_to "Edit", edit_warehouse_path(warehouse) %>
          <%= link_to "Delete",
                      warehouse_path(warehouse),
                      class: "delete",
                      method: :delete,
                      data: {
                        confirm: "Are you sure you want to delete this warehouse?"
                      } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/warehouses/new.html.erb
<div class="container">
  <h1>New Warehouse</h1>

  <%= render "form", warehouse: @warehouse %>
</div>

app/views/warehouses/show.html.erb
<h1>Warehouse</h1>
<hr />
<table class="table">
  <tbody>
    <tr>
      <td>Street</td>
      <td id="warehouse--<%= @warehouse.id %>_street">
        <%= @warehouse.street %>
      </td>
    </tr>
    <tr>
      <td>City</td>
      <td id="warehouse--<%= @warehouse.id %>_city">
        <%= @warehouse.city %>
      </td>
    </tr>
    <tr>
      <td>Province</td>
      <td id="warehouse--<%= @warehouse.id %>_province">
        <%= @warehouse.province %>
      </td>
    </tr>
  </tbody>
</table>